-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQQT4XE7HOdxiHOBE
bm5DyMBsD5KYJQ8x4RsfUzvFJnSgCgYIKoZIzj0DAQehRANCAATkdA/0xI6QPJPE
JJlulbuqlk6J0yYYeFBdh9AXOvlFOo941bEzRxkj6tR1WdKzW1ZG1hmLzIKJuYhO
R5Zk5Hap
-----END PRIVATE KEY-----